### ISSUE TITLE
Problem: 应该如何彻底解决下载问题？(i.e. P1&P2)

### ISSUE THREAD

**Issue by teaSummer** [teaSummer/MCiSEE#2]
### Problem: 应该如何彻底解决下载问题？(i.e. P1&P2)

GitHub 文件加速下载[^1]、网盘直链解析[^2] 等类似的服务很难长期维持正常 + 保证下载速度。

那么，如何彻底解决P1[^1]、P2[^2] 就成了两大难题，因为不是所有用户都有 VPN，以及网盘手动下载的耐心。

诚心希望大家能够积极参与问题讨论，非常感谢。

---

### Problem: How to solve download problems for good? (i.e. P1&P2)

GitHub File Accelerate Downloading[^1], Network Disk Parsing Direct Download Link[^2] and similar services are difficult to maintain normal for a long time + to ensure download speed.

Then, how to completely solve P1[^1], P2[^2] has become two major problems, because not all users have VPN, and the patience of manual download.

I sincerely hope that you can actively participate in the discussion, thank you very much.

[^1]: `GitHub 文件加速下载` 问题，简写为 P1。 | `GitHub File Accelerate Downloading` Problem, abbreviated as P1.
[^2]: `网盘直链解析` 问题，简写为 P2。 | `Network Disk Parsing Direct Download Links` Problem, abbreviated as P2.

**Comment by XiaozhiSans** [comment]
仓库代理就用`jsdelivr`挺好的

**Comment by teaSummer** [comment]
P1：暂时使用 (GitHub 文件加速)[https://gh.api.99988866.xyz] 服务代替，期待更好的解决方案。

**Comment by XiaozhiSans** [comment]
哦~ (摆烂

**Comment by teaSummer** [comment]
P1：采用临时方案 https://sciproxy.com，多个网站待测速。

**Comment by teaSummer** [comment]
或许会有机会在服务器解决 P1、P2，暂时以未计划关闭该 Issue。

**Comment by teaSummer** [comment]
@baiyuncode 预计会在将来对 P1 作出处理。
已将此 Issue 划为 “待处理” “重要” 事项。

**Comment by XiaozhiSans** [comment]
＜（＾－＾）＞

**Comment by baiyuncode** [comment]
已经迁移到服务器上

**Comment by XiaozhiSans** [comment]
> 已经迁移到服务器上

那么how 2 use

**Comment by teaSummer** [comment]
> 已经迁移到服务器上

@baiyuncode 我好像没有看到网站有什么改动，能说明一下吗？

具体请见该 Issue 的描述。此 Issue 在没有说明改动的情况下，不应该被完成

**Comment by XiaozhiSans** [comment]
> > 已经迁移到服务器上
> 
> @baiyuncode 我好像没有看到网站有什么改动，能说明一下吗？
> 
> 并且在实际场景中无法应用，没有解决 P1 和 P2，具体请见该 Issue 的描述。
> 
> 该 Issue 在没有说明改动的情况下，不应该被完成。
> 
> 另外，若您只解决了 P1 或 P2 其中之一，请将事项进度设为 `50%` 而不是完成它。

![image](https://github.com/teaSummer/MCiSEE/assets/127290936/0b4d846f-e1e7-4390-a8bc-caafe08896f2)
*man*! **what** can i **say**?

**Comment by teaSummer** [comment]
牢大居然在 _24_ 年复活了！(

**Comment by teaSummer** [comment]
P2：目前，我发现 [netdisk-fast-download](https://github.com/qaiu/netdisk-fast-download) 的项目地址 https://lz.qaiu.top 正常运转，并且或许能够进行直链解析了。

---

P2: Now, I find [netdisk-fast-download](https://github.com/qaiu/netdisk-fast-download)'s website https://lz.qaiu.top working successfully, and may be able to Parse Direct Download Links.

**Comment by XiaozhiSans** [comment]
> P2：我发现 [netdisk-fast-download](https://github.com/qaiu/netdisk-fast-download) 的项目地址 https://lz.qaiu.top 正常运转，或许能够进行直链解析了。
> 
> P2: I found that [netdisk-fast-download](https://github.com/qaiu/netdisk-fast-download)'s website https://lz.qaiu.top up, it may be able to parse direct download links.

这都被你找到了(

---
you found it?(

**Comment by XiaozhiSans** [comment]
还不睡觉(

**Comment by teaSummer** [comment]
> 还不睡觉(

草，你也不没睡(

再叫看你本(?

**Comment by XiaozhiSans** [comment]
我觉得可以在服务器上部署 [hanximeng/LanzouAPI](https://github.com/hanximeng/LanzouAPI)
来解决蓝奏云下载问题

i think we can install [hanximeng/LanzouAPI](https://github.com/hanximeng/LanzouAPI) on the server
to solve the download problem of lanzouyun

---

示例站点 / demo site:
[`https://api.hanximeng.com/lanzou/`](https://api.hanximeng.com/lanzou/)

---

使用例 / 返回值:
example / return:
```bash
~ $ curl -i "https://api.hanximeng.com/lanzou/?url=https://ruansky-xiaozhi.lanzouw.com/iCq0h1lo6vva"
HTTP/2 200 
server: nginx
date: Tue, 02 Jul 2024 17:31:12 GMT
content-type: application/json; charset=utf-8
vary: Accept-Encoding
access-control-allow-origin: *
strict-transport-security: max-age=31536000
alt-svc: quic=":443"; h3-27=":443";h3-25=":443"; h3-T050=":443"; h3-Q050=":443";h3-Q049=":443";h3-Q048=":443"; h3-Q046=":443"; h3-Q043=":443"

{
    "code": 200,
    "msg": "解析成功",
    "name": "imz2_v2.0.0_beta_lite.zip",
    "fileauthor": "XiaozhiSans",
    "filesize": "59.3 K",
    "filedate": "2024-01-20",
    "fileinfo": "前一个lite版不知怎么下不了，补发的",
    "downUrl": "https://s-02.lanzog.com:446/07030100159060560bb/2024/01/20/fe42eb6616e4d4c49ad92e9f27f1b931.zip?st=JsU3EVaheQHtoG5b_cyBzw&e=1719941772&b=Vm0MYQN5VmFRW19_aC2kHLQJnDH4ENVYPBjcOZgFyUDMCDw1hAGkAcQIyAHgBK1I_aVHE_c&fi=159060560&pid=66-70-73-236&up=2&mp=0&co=0",
    "tips": "该次请求使用的缓存"
}
```

**Comment by teaSummer** [comment]
> 我觉得可以在服务器上部署 [hanximeng/LanzouAPI](https://github.com/hanximeng/LanzouAPI) 来解决蓝奏云下载问题
> 
> i think we can install [hanximeng/LanzouAPI](https://github.com/hanximeng/LanzouAPI) on the server to solve the download problem of lanzouyun
> 
> 示例站点 / demo site: [`https://api.hanximeng.com/lanzou/`](https://api.hanximeng.com/lanzou/)
> 
> 使用例 / 返回值: example / return:
> 
> ```shell
> ~ $ curl -i "https://api.hanximeng.com/lanzou/?url=https://ruansky-xiaozhi.lanzouw.com/iCq0h1lo6vva"
> HTTP/2 200 
> server: nginx
> date: Tue, 02 Jul 2024 17:31:12 GMT
> content-type: application/json; charset=utf-8
> vary: Accept-Encoding
> access-control-allow-origin: *
> strict-transport-security: max-age=31536000
> alt-svc: quic=":443"; h3-27=":443";h3-25=":443"; h3-T050=":443"; h3-Q050=":443";h3-Q049=":443";h3-Q048=":443"; h3-Q046=":443"; h3-Q043=":443"
> 
> {
>     "code": 200,
>     "msg": "解析成功",
>     "name": "imz2_v2.0.0_beta_lite.zip",
>     "fileauthor": "XiaozhiSans",
>     "filesize": "59.3 K",
>     "filedate": "2024-01-20",
>     "fileinfo": "前一个lite版不知怎么下不了，补发的",
>     "downUrl": "https://s-02.lanzog.com:446/07030100159060560bb/2024/01/20/fe42eb6616e4d4c49ad92e9f27f1b931.zip?st=JsU3EVaheQHtoG5b_cyBzw&e=1719941772&b=Vm0MYQN5VmFRW19_aC2kHLQJnDH4ENVYPBjcOZgFyUDMCDw1hAGkAcQIyAHgBK1I_aVHE_c&fi=159060560&pid=66-70-73-236&up=2&mp=0&co=0",
>     "tips": "该次请求使用的缓存"
> }
> ```

....

或许同样可以在服务器上部署 [qaiu/netdisk-fast-download](https://github.com/qaiu/netdisk-fast-download)？
好处是：支持更多网盘。如小飞机盘（免费、支持免登录下载 + 100M以上）

**Comment by teaSummer** [comment]
@baiyuncode 考虑在服务器部署一些项目？

**Comment by teaSummer** [comment]
P1: 改用 https://ghproxy.cn | Change to https://ghproxy.cn

**Comment by baiyuncode** [comment]
I think this a good way

**Comment by XiaozhiSans** [comment]
怎么漏了个is(

**Comment by teaSummer** [comment]
如有疑问，请在此留言，谢谢。

**Comment by teaSummer** [comment]
此问题已大致解决，目前正在审查中。  
正常情况下，我们会在审查30天后修改至完成状态。

若仍有疑问，请在此留言，谢谢。
