### ISSUE TITLE
[i18n] 关于 en.yml

### ISSUE THREAD

**Issue by XiaozhiSans** [teaSummer/MCiSEE#5]
我发现 AutoLang(以下简称'al') 貌似是直接获取 `navigator.language // 'zh-CN'` 作为地区码

这就导致一个**问题**:
要是语言**一致**,国家**不同**的地区是不是要复制粘贴**同一份**文件?

举个栗子, 美利坚人访问 `mcisee.top`, `navigator.language` 会返回 `'en-US'`
大嘤人访问就会返回 `'en-GB'`
假设而我们只有 `en-US.yml` 和 `zh-CN.yml` 那大嘤人看什么?看 `zh-CN.yml` 吗?

我这里给出几个解决方案:
  1. 叫 al 的开发者支持一下模糊匹配
  2. 我们自己写一个模糊匹配规则 (比如获取 `navigator.language` 后遍历一下语言文件数组看看对应的语言文件是否存在,存在就直接载入,否则匹配 `navigator.language.split('-')[0]` 否则 `navigator.language.split('-')[0]-US` ~~*你明白吗 看不清楚 该罚*~~)
  3. 或者干脆直接改用 `navigator.language.split('-')[0]` 得了 ~~*我是nba2k玩家,这就事投篮罢*~~

&emsp;~~4. *事已至此,直接开摆*~~

**Comment by XiaozhiSans** [comment]
哦对了可以按`f12`打开控制台输入
```js
al.load('en');
```
看效果

**Comment by teaSummer** [comment]
@TheChuan1503 请见此 Issue

**Comment by teaSummer** [comment]
不过实际上，`en-US` 和  `en-GB` 有细微差距的（

我觉得分开写也没什么问题

**Comment by teaSummer** [comment]
使用 `default_country`，如下图：

![dca0bcb454516660e67600820df411a6](https://github.com/teaSummer/MCiSEE/assets/144581741/5024beb1-f57a-4d36-8d2a-72b800d538bd)

**Comment by XiaozhiSans** [comment]
> 不过实际上，`en-US` 和 `en-GB` 有细微差距的（
> 
> 我觉得分开写也没什么问题

我觉得大嘤人不至于看不懂美式英语,毕竟人家mc的语言文件中`en_US.lang`和`en_GB.lang`貌似事同一份文件(

**Comment by TheChuan1503** [comment]
使用
```javascript
al.setDefaultCountry({
    en:"en-US",
    zh:"zh-CN"
})
```
或在语言文件中设置
```json
"default_country":{
    "en":"en-US",
    "zh":"zh-CN"
}
```

**Comment by XiaozhiSans** [comment]
既然有解决方案了那就关了罢

**Comment by teaSummer** [comment]
与 MCiSEE Todo List 关联弱（未提及 MCiSEE），此 Issue 已被移出。

**Comment by XiaozhiSans** [comment]
一定是 github-project-automation[bot] 干的(

**Comment by teaSummer** [comment]
> 一定是 github-project-automation[bot] 干的(

草
